name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite correr tu Action manualmente desde la página de GitHub

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Obtener Repositorio
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Habilitar Flutter Desktop
        run: flutter config --enable-windows-desktop

      - name: Instalar Dependencias
        run: flutter pub get

      - name: Compilar para Windows (.exe)
        run: flutter build windows --release

      - name: Subir Archivo a GitHub (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: mercadopago-visualizer-windows
          path: build/windows/x64/runner/Release/
